recipe_box/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recipes

  root "recipes#index"
end

recipe_box/app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

recipe_box/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

recipe_box/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "400px x 400 px>#"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_many :ingredients
  has_many :directions
  belongs_to :user
  accepts_nested_attributes_for :ingredients, 
                                reject_if: proc{|attributes| attributes['name'].blank?}, 
                                allow_destroy: true
  accepts_nested_attributes_for :directions, 
                                reject_if: proc{|attributes| attributes['step'].blank?}, 
                                allow_destroy: true
  validates :title, :description, :image , presence: true
end

recipe_box/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes
end

recipe_box/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

recipe_box/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	before_action :find_recipe, only: [:show,:edit,:update,:destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@recipes = Recipe.all.order("created_at DESC")
	end

	def show
	end

	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)

		if @recipe.save
			redirect_to @recipe, notice: "Succesfully created new recipe"
		else 
			render 'new'
		end 
	end

	def edit
		
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else 
			render 'edit'
		end 
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Successfully deleted the recipe"
	end

	 

	private 

	def find_recipe
		@recipe = Recipe.find_by(id: params[:id])
	end 

	def recipe_params
		params.require(:recipe).permit(:title, :description, :image,
			                           ingredients_attributes: [:id, :name, :_destroy],
			                           directions_attributes: [:id, :step, :_destroy]
			                           )
	end
end

recipe_box/app/helpers/application_helper.rb
module ApplicationHelper
end

recipe_box/app/helpers/recipes_helper.rb
module RecipesHelper
end

recipe_box/app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Recipe Box
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Recipe Box", root_path
      
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Recipe", new_recipe_path
          %li= link_to "Sign out", destroy_user_session_path, method: :delete
      - else 
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path

  .container
    -flash.each do|name,msg|
      = content_tag :div,msg,class: "alert"

    = yield

recipe_box/app/views/recipes/_direction_fields.html.haml
.form-inline-clearfix
  .nested_fields
    = f.input :step, input_html: {class: 'form-input form-control'}
    = link_to_remove_association "Remove Step", f, class: "form-button btn btn-default"
    

recipe_box/app/views/recipes/_form.html.haml
= simple_form_for @recipe, hthl: {multipart: true} do |f|
  - if @recipe.errors.any?
    #errors
      %p
        = @recipe.errors.count prevented from saving
      %ul
        - @recipe.errors.full_messages.each do |msg|
          %li = msg
  .panel-body
    = f.input :title, input_html: {class: 'form-control'}
    = f.input :description, input_html: {class: 'form-control'}
    = f.input :image, input_html: {class: 'form-control'}

    .row 
      .col-md-6
        %h3 Ingredients
        #ingredients
          = f.simple_fields_for :ingredients do |ingredient|
            = render 'ingredient_fields', f: ingredient
          .links
            = link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"

      .col-md-6
        %h3 Directions
        #directions
          = f.simple_fields_for :directions do |direction|
            = render 'direction_fields', f: direction
          .links 
            = link_to_add_association 'Add Direction', f, :directions, class: "btn btn-default add-button"
  = f.button :submit, class: "btn btn-primary"

recipe_box/app/views/recipes/_ingredient_fields.html.haml
.form-inline-clearix
  .nested_fields
    = f.input :name, input_html: {class: "form-input form-control"}
    = link_to_remove_association "Remove", f, class: "form-button btn btn-default"

recipe_box/app/views/recipes/edit.html.haml
%h1 Edit Recipe
= render 'form'

recipe_box/app/views/recipes/index.html.haml
- @recipes.each_slice(3) do |recipes|
  .row
    - recipes.each do |recipe|
      .col-md-4
        .recipe
          .image-wrapper
            = link_to recipe do
              = image_tag recipe.image.url(:medium)
            %h2= link_to recipe.title, recipe

recipe_box/app/views/recipes/new.html.haml
%h1 New Recipe
= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

recipe_box/app/views/recipes/show.html.haml
.main-content
  #recipe_top.row
    .col-md-4
      = image_tag @recipe.image.url(:medium, class: "recipe-image")
    .col-md-8
      #recipe_info
        %h1= @recipe.title
        %p.descripion= @recipe.description
        %p.description= @recipe.user.email
  .row 
    .col-md-6
      #ingredients
        %h2 Ingredients
        %ul
          - @recipe.ingredients.each do|ingredient|
            %li= ingredient.name
    .col-md-6
      #directions
        %h2 Directions
        %ul
          - @recipe.directions.each do|direction|
            %li= direction.step

  .row 
    .col-md-12
      = link_to "Back",root_path, class: "btn btn-default"
      - if user_signed_in?
        = link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-default"
        = link_to "Delete", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"